### ISSUE TITLE
Are there demos or examples?

### ISSUE THREAD

**Issue by dcy** [shopgun/turtle#14]
Hi!
I want to use turtle.
But I don't know how to use, It is better if there is a tutorial.
Are there demos or examples of how to use turtle?
Thanks!

**Comment by jlouis** [comment]
At the time of this writing, there is only documentation. The alternative is to look inside the `test` directory for the test cases, which documents at least one use of the library, though some uses in there are less idiomatic than what they could be.

**Comment by jlouis** [comment]
A good example would be a ping/pong system where you can send a "ping" and a service answers with "pong".
