### ISSUE TITLE
how to use turtle:publish?

### ISSUE THREAD

**Issue by dcy** [shopgun/turtle#15]
Hi!
```
-module(rmqc).
-export([send/0,
		 gen_publish/0,
		 publish/0
		]).
-include_lib("amqp_client/include/amqp_client.hrl").

gen_publish() ->
	turtle_publisher:start_link(my_publisher, amqp_server,
								[#'exchange.declare' { exchange = <<"test">>},
								 #'queue.declare' { queue = <<"hello">>},
								 #'queue.bind' { queue = <<"hello">>, exchange = <<"test">>, routing_key = <<"hello">> }],
								#{ confirms => true} ),
	ok.

publish() ->
	Result = turtle:publish(my_publisher, <<"test">>, <<"hello">>, <<"text/plain">>, <<"Hello World!">>),
	lager:error("**********Result: ~p", [Result]),
	ok.


send() ->
    {ok, Connection} =
        amqp_connection:start(#amqp_params_network{host = "localhost"}),
    {ok, Channel} = amqp_connection:open_channel(Connection),

    %amqp_channel:call(Channel, #'queue.declare'{queue = <<"hello">>}),

    amqp_channel:cast(Channel,
                      #'basic.publish'{
                        exchange = <<"">>,
                        routing_key = <<"hello">>},
                      #amqp_msg{payload = <<"Hello World!">>}),
    io:format(" [x] Sent 'Hello World!'~n"),
    ok = amqp_channel:close(Channel),
    ok = amqp_connection:close(Connection),
	ok.
```
```send/0``` use amqp_client, ```publish/0``` use turtle, it woks both.
Am i right in using ```turtle:publish/5```?

**Comment by jlouis** [comment]
Yes, though your earlier solution with `turtle_publisher:child_spec/4` is more idiomatic for an OTP application. The idea is to use the `child_spec` to get a specification you can add to your own applications `supervisor`. Once your app boots, the publisher is then also started.

Next you use `turtle:publish/5` more or less like you do. Note the advantage of splitting these two operations: Connections and Channel creation is decoupled from usage. And your supervision tree manage automatic restarts under failure. Whereas the above two examples will create a new connection to the RabbitMQ server every time you call them.

**Comment by dcy** [comment]
```
gen_publish() ->
	turtle_publisher:start_link(my_publisher, amqp_server,
								[#'exchange.declare' { exchange = <<"test">>},
								 #'queue.declare' { queue = <<"test_turtle">>},
								 #'queue.bind' { queue = <<"test_turtle">>, exchange = <<"test">>, routing_key = <<"turtle">> }],
								#{ confirms => true} ),
	ok.

child_spec_gen_publish() ->
	AMQPDecls = [#'exchange.declare' { exchange = <<"test">>},
				 #'queue.declare' { queue = <<"test">>},
				 #'queue.bind' {queue = <<"test">>, exchange = <<"test">>, routing_key = "test"}
				],
	turtle_publisher:child_spec(my_publisher, amqp_server, AMQPDecls, #{ confirms => true}),
	ok.
```
What's the difference between them? ```gen_pulbish``` will add the queue ```turtle_test```, and ```child_spec_gen_publish``` will not add the queue ```test```

**Comment by jlouis** [comment]
Can you show the surrounding supervisor code in which you insert the output of `child_spec_gen_publish()` ? It looks right from a quick glance, so I am wondering if it is used correctly in context.

**Comment by ptrf** [comment]
What happens if you explicitly set passive => true in your Options for the latter?

**Comment by dcy** [comment]
Sorry! i forget these:
```
	ChildSpec = turtle_publisher:child_spec(my_publisher, amqp_server, AMQPDecls, #{ confirms => true}),
	supervisor:start_child(turtle_sup, ChildSpec),
```
After these, it will create a process in turtle_sup, maybe this is better than ```turtle_publisher:start_link```

**Comment by dcy** [comment]
By the way! how can i use turtle to do [Worker Queue](https://www.rabbitmq.com/tutorials/tutorial-two-python.html), because trutle only have one process one connection?

**Comment by jlouis** [comment]
A worker queue will have a sender and a receiver. You create a `turtle_publisher` for the sender and a `turtle_service` for the receiving end. Then you write a handler for the service end and you are essentially done.

Publication is non-blocking, asynchronous and fast, so a single publisher usually runs more than 50k messages/sec in my tests. Receiving and handling work depends on how hard it is for you to handle work, and your blocking behaviour. You may want to set prefetch counts and worker counts accordingly depending on the amount of simultaneous work you want to allow in your system.
