### ISSUE TITLE
rabbitmqctl stop_app about "add publisher child to turtle_sup"

### ISSUE THREAD

**Issue by dcy** [shopgun/turtle#22]
Hi!
Can't i add my subscriber or publisher to turtle_sup?
In my test.  The subscribers works fine for `rabbitmqctl stop_app`, it will reconnect after `rabbitmqctl start_app`. It work well.
But it does not work for publisher.

```
                  AMQPChildSpec = turtle_publisher:child_spec(Type, ConnName, AMQPDecls,
                                                                  #{ confirms => true}), 
                  supervisor:start_child(turtle_sup, AMQPChildSpec)

```

It does not work. The Application turtle will shutdown. There are many error log:

```
17:43:19.151 [error] Supervisor turtle_sup had child apns started with turtle_publisher:start_link(apns, amqp_server, [], #{confirms => true}) at <0.2640.0> exit with reason {{shutdown,{connection_closing,{server_initiated_close,320,<<"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'">>}}},{gen_server,call,[<0.2678.0>,{close,200,<<"Goodbye">>},infinity]}} in context shutdown_error
17:43:19.211 [info] Application turtle exited with reason: shutdown
```

but it works when i change `turtle_sup` to ``another_sup`.
Could you tell me can i add subscriber or publisher to turtle_sup?

**Comment by jlouis** [comment]
Is still still a relevant case? I'm not sure what is going on in your end, so in order to help you I need more information about what is happening.

**Comment by dcy** [comment]
It works when i do not start child with ```turtle_sup```.
With ```turtle_sup```, the turtle will shutdown when the rabbitmq restart
