### ISSUE TITLE
Spec for turtle's public APIs

### ISSUE THREAD

**Issue by sdebnath** [shopgun/turtle#5]
Currently, only declare/2 and open_channel/1 is spec'ed. 

Need specs for:
- publish/5,
- publish/6,
- publish_sync/5,
- publish_sync/6,
- rpc/5,
- rpc_await/3,
- rpc_await_monitor/3,
- rpc_cancel/2,
- rpc_sync/5,
- rpc_sync/6
- consume/2,
- cancel/2,
- qos/2

**Comment by jlouis** [comment]
We can probably skip `consume/2`, `cancel/2` and `qos/2` because they are all private functions for internal use. In fact, one might consider moving them out of the `turtle` module. The remaining could use specs though.

**Comment by jlouis** [comment]
This should be done in commit 162fec4c6ba249b3393325e which includes specifications for the necessary functions. I've also moved the `@private` marked functions into their own section in the source code.

**Comment by jlouis** [comment]
This has been done.
